### ISSUE TITLE
Orientation changes call scrollToPosition(0) to be called

### ISSUE THREAD

**Issue by codinginflow** [googlecodelabs/android-paging#100]
Orientation changes seem to trigger the `loadStateFlow` so that `scrollToPosition(0)` gets called. The same happens when you use it in a fragment and the view is recreated.

**Comment by 1298se** [comment]
For the fragment view recreated issue, this can be solved by calling launchWhenStarted in the onCreate or init of the fragment

**Comment by tunjid** [comment]
@codinginflow does this happen if you use the `cachedIn` [operator](https://developer.android.com/reference/kotlin/androidx/paging/package-summary#(kotlinx.coroutines.flow.Flow).cachedIn(kotlinx.coroutines.CoroutineScope)) with a `ViewModel`?

**Comment by codinginflow** [comment]
@tunjid yes

**Comment by tunjid** [comment]
@codinginflow taking a closer look, it's because the trigger for the scroll to the top is on the adapter which is recreated during orientation changes or when the `Fragment` is recreated.

To fix this, you can keep track of the last query in the `ViewModel` and only scroll to the top if:

1. loadState.refresh is LoadState.NotLoading
2. The query hasn't from the last query before the view recreation.

I'll update the codelab with this as soon as I'm able to.

**Comment by tunjid** [comment]
@codinginflow this has been fixed in the codelab now. You may need to re clone the repo as there was quite a lot of rebasing done. Closing the issue now, lemme know if you have any more concerns.
