### ISSUE TITLE
How to get resonse using suspend or Coroutine from WebScoket

### ISSUE THREAD

**Issue by hemant1109** [googlecodelabs/android-paging#148]
I have question about getting response for paging data from web socket.
In Below file.
(**https://github.com/googlecodelabs/android-paging/blob/step13-19_network_and_database/app/src/main/java/com/example/android/codelabs/paging/data/GithubRemoteMediator.kt**).

line:  78 is as below

"**val apiResponse = service.searchRepos(apiQuery, page, state.config.pageSize)**".

Where suspend is used with retrofit and give response in one line.

I want to do same thing for Web Socket.
I am using OkHttpClient for Web socket connection,

**Comment by dlam** [comment]
`RemoteMediator` is only needed if you "pull"-based way of triggering remote requests to fetch more data. It's basically a way to hook into Paging running out of data and needing more from network, but it has no direct bearing on what drives Paging itself, that is all based on `PagingSource`.

Instead, the way `RemoteMediator` works is by inserting into DB backing `PagingSource`, and letting Paging pickup the changes naturally via invalidation (`PagingSource.invalidate()`), so similarly your WS listener will just listen for new items and insert into DB, then invalidate.

If you need to send a request through your WS to get data from it, then you just do that in `RemoteMediator` and return `RemoteMediator.Success()`, if you have a separate signal to trigger remote loads, you don't need `RemoteMediator` at all.

One more thing - `RemoteMediator.Success()` takes in a `endOfPaginationReached` argument which prevents Paging from making requests after you hit the end of the list, so you may need to create an implementation which awaits a message from WS listener before returning so you can fill in `endOfPaginationReached` correctly. Since `RemoteMediator.load()` is suspending, you have a few options to convert, but one simple way is to use suspendCancellableCoroutine builder described similarly here: https://discuss.kotlinlang.org/t/generic-function-to-wrap-callbacks-with-coroutines/8885

**Comment by hemant1109** [comment]
> `RemoteMediator` is only needed if you need a "pull"-based way of triggering remote requests to fetch more data. It's basically a way to hook into Paging running out of data and needing more from network, but it has no direct bearing on what drives Paging itself, that is all based on `PagingSource`.
> 
> Instead, the way `RemoteMediator` works is by inserting into DB backing `PagingSource`, and letting Paging pickup the changes naturally via invalidation (`PagingSource.invalidate()`), so similarly your WS listener will just listen for new items and insert into DB, then invalidate.
> 
> If you need to send a request through your WS to get data from it, then you just do that in `RemoteMediator` and return `RemoteMediator.Success()`, if you have a separate signal to trigger remote loads, you don't need `RemoteMediator` at all.
> 
> One more thing - `RemoteMediator.Success()` takes in a `endOfPaginationReached` argument which prevents Paging from making requests after you hit the end of the list, so you may need to create an implementation which awaits a message from WS listener before returning so you can fill in `endOfPaginationReached` correctly. Since `RemoteMediator.load()` is suspending, you have a few options to convert, but one simple way is to use suspendCancellableCoroutine builder described similarly here: https://discuss.kotlinlang.org/t/generic-function-to-wrap-callbacks-with-coroutines/8885

Thank you so much @dlam. It works for me.
