### ISSUE TITLE
Data doesn't display after saving from network when in offline mode

### ISSUE THREAD

**Issue by Mehul-Bisht** [googlecodelabs/android-paging#170]
Once data is loaded from Network via the Remote Mediator into the `Room` database, it should display that for both online and offline modes. But in the branch: `step13-19_network_and_database`, when running the code from the codelab I found that there is no data displayed when the device is offline. I am attaching a gif as a visual representation of this issue below.

**Comment by CelikAbdullah** [comment]
I think it is because of the 'binding.list.isVisible = loadState.mediator?.refresh is LoadState.NotLoading' line in the Activity class. In offline mode, the loading state of the mediator is LoadState.Error so that the expression above is False which then makes the list invisible. 

I had the same issue and provided a solution for this [here](https://github.com/googlecodelabs/android-paging/issues/169). It worked for me so you could try it until some of the official developers of the Paging library provide a solution for this.

**Comment by Mehul-Bisht** [comment]
![paging_error](https://user-images.githubusercontent.com/65572088/119346508-eca1dd00-bcb7-11eb-9746-680b1e59d195.gif)

**Comment by Mehul-Bisht** [comment]
> I think it is because of the 'binding.list.isVisible = loadState.mediator?.refresh is LoadState.NotLoading' line in the Activity class. In offline mode, the loading state of the mediator is LoadState.Error so that the expression above is False which then makes the list invisible.
> 
> I had the same issue and provided a solution for this [here](https://github.com/googlecodelabs/android-paging/issues/169). It worked for me so you could try it until some of the official developers of the Paging library provide a solution for this.

Will try it out, @florina-muntenescu suggested me on twitter to open an issue for this :)

**Comment by Mehul-Bisht** [comment]
@CelikAbdullah this solution works as expected. Maybe try mentioning some contributor so they are aware of this change!

**Comment by CelikAbdullah** [comment]
@Mehul-Bisht : I am glad that I could help you. Now, I also mentioned @florina-muntenescu  in my thread. Maybe she or other contributors change the official code.

**Comment by tunjid** [comment]
@Mehul-Bisht @CelikAbdullah thanks for your feedback on this, it was fixed in https://github.com/googlecodelabs/android-paging/pull/175
