### ISSUE TITLE
data synchronization error in repository between database data and network

### ISSUE THREAD

**Issue by angelmarrugo** [googlecodelabs/android-paging#196]
To better understand me, follow these simple steps:
1. After it shows the list of repositories that match the query `Android`, start another search with the word for example` chicken`.
2. Followed by that start another search with the word `Facebook` for example.
3. Finally, start another search with `Android` again. What will repos based on the results of the last query stored in the DB.

**Comment by tunjid** [comment]
@angelmarrugo This  likely is a rate limiting error. As we are using the unauthenticated github API, we can only make a certain amounts of requests in a certain time frame otherwise we get a 403. That said, we should still be able to fetch the data cached in the DB even though remote fetch fails. I'll look into this some more.

**Comment by angelmarrugo** [comment]
Hello Tunjid, you are right. now it's so easy for me to see it. But when I wrote this I was learning and I didn't understand it. I had forgotten to close this. Thanks for the guide, it made it easier for me to understand paging3 :)
