### ISSUE TITLE
gradle project sync failed

### ISSUE THREAD

**Issue by corinzio** [googlecodelabs/android-paging#20]
when i built the project i got this error:

> API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.

To get rid of it i had to update ext.kotlin_version from 1.2.71 to 1.3.10

thanks

**Comment by ataulm** [comment]
This doesn't happen on the stable version of Android Studio (3.2.1).

If you're on a dev/canary version of Android Studio, it'll want you to update your Android Gradle Plugin, which is what requires you to update both your Gradle wrapper and the Kotlin Gradle Plugin:

> ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
> The following dependencies do not satisfy the required version:
> root project 'android-paging' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
> Affected Modules: app

**Comment by OliPro007** [comment]
Did you download the project from the codelab page or did you clone this repo? The zip on the codelab page is severely outdated, while the issues seems to have been fixed in the repo (at least it works fine for me). I suggest you clone the repo instead of messing manually with the outdated configs.

Google should either update the zip on the codelab or put the clone url like they did for the coroutines.

**Comment by florina-muntenescu** [comment]
Link to the zip in the codelab was updated.
