### ISSUE TITLE
Retrofit2 403 Rate limit exceeded

### ISSUE THREAD

**Issue by 2000Vlad** [googlecodelabs/android-paging#87]
When scrolling very fast, HTTP 403 Rate limit exceeded is thrown

**Comment by jsouza678** [comment]
It´s normal because GitHub api has a limit of Requests.. If you application is correct, like the example, you should have this problem when scroll fast at least 3 times...
The workaround for it (at least that´s what Github says on api), is: authentication.
https://developer.github.com/v3/rate_limit/

**Comment by florina-muntenescu** [comment]
It's Github's limit, as @jsouza678 pointed out.
